{{- if eq .Values.nacos.storage.type "mysql"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.nacos.storage.db }}
  mysql.db.host: {{.host}}
  mysql.db.name: {{ .name }}
  mysql.port: "{{ .port | default 3306}}"
  mysql.user: {{ .username }}
  mysql.password: {{ .password }}
  mysql.param: {{ .param | default "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false" }}
  {{- end }}
  {{- if .Values.auth.enable }}
  auth.token: {{.Values.auth.token}}
  auth.server.identity.key: {{.Values.auth.server.identity.key}}
  auth.server.identity.value: {{.Values.auth.server.identity.value}}
  {{- end }}
{{- end }}