{{- if and (eq .Values.global.mode "cluster") }}
apiVersion: v1
kind: Service
metadata:
  name: nacos-hs
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.nacos.serverPort }}
      targetPort: {{ .Values.nacos.serverPort }}
      protocol: TCP
      name: http
    - port: {{add .Values.nacos.serverPort 1000}}
      name: client-rpc
      targetPort: {{add .Values.nacos.serverPort 1000}}
    - port: {{add .Values.nacos.serverPort 1001}}
      name: raft-rpc
      targetPort: {{add .Values.nacos.serverPort 1001}}
  selector:
    app.kubernetes.io/name: {{ include "nacos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- if .Values.clientService.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-cs
  namespace: {{ .Values.namespace }}
  labels:
  {{- toYaml .Values.clientService.labels | nindent 4 }}
  annotations:
  {{- toYaml .Values.clientService.annotations | nindent 4 }}
spec:
  type: {{ .Values.clientService.type }}
  ports:
    - port: {{ .Values.nacos.serverPort }}
      targetPort: {{ .Values.nacos.serverPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.clientService.nodePortHttp }}
    - port: {{add .Values.nacos.serverPort 1000}}
      name: client-rpc
      targetPort: {{add .Values.nacos.serverPort 1000}}
      nodePort: {{ .Values.clientService.nodePortGrpc }}
  selector:
    app.kubernetes.io/name: {{ include "nacos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
